import { validateEmail, validateRequired, validateCPF, validateMobile } from '../../../utils';
import { Dimensions } from 'react-native';
const { width: winWidth } = Dimensions.get('window');

export const formData = [
  {
    name: 'nome',
    label: 'Nome Completo',
    width: '100%',
    required: true,
    validate: [validateRequired],
    next: true,
    keyboardType: 'default',
    textContentType: 'none',
    autoCapitalize: 'words',
    inputType: 'text',
    group: 'dados_pessoais'
  },
  {
    name: 'cpf',
    label: 'CPF',
    width: '100%',
    required: true,
    maxLength: 14,
    format: 'cpf',
    validate: [validateRequired, validateCPF],
    next: false,
    hint: 'Digite apenas números',
    keyboardType: 'numeric',
    textContentType: 'none',
    disabledOnEdit: false,
    inputType: 'text',
    group: 'dados_pessoais'
  },
  {
    name: 'estado_civil',
    label: 'Estado Civil',
    width: '100%',
    required: true,
    validate: [validateRequired],
    group: 'dados_pessoais',
    inputType: 'select',
    options: 'estadoCivilList'
  },
  {
    name: 'nacionalidade',
    label: 'Nacionalidade',
    width: '100%',
    required: true,
    validate: [validateRequired],
    group: 'dados_pessoais',
    inputType: 'select',
    options: 'nacionalidadeList'
  },
  {
    name: 'profissao',
    label: 'Profissão',
    width: '100%',
    required: true,
    validate: [validateRequired],
    group: 'dados_pessoais',
    inputType: 'autocomplete'
  },
  {
    name: 'sexo',
    label: 'Sexo',
    width: '100%',
    required: true,
    validate: [validateRequired],
    group: 'dados_pessoais',
    inputType: 'select',
    options: 'sexoList'
  },
  {
    name: 'celular',
    label: 'DDD e Celular',
    width: winWidth <= 360 ? '100%' : '50%',
    required: true,
    maxLength: 15,
    format: 'ddd-mobile',
    validate: [validateRequired],
    next: true,
    hint: '(99) 99999 9999',
    keyboardType: 'numeric',
    textContentType: 'none',
    inputType: 'text',
    group: 'dados_pessoais'
  },
  {
    name: 'telefone_fixo',
    label: 'DDD e Tel. Fixo',
    width: winWidth <= 360 ? '100%' : '47%',
    required: false,
    maxLength: 14,
    format: 'ddd-phone',
    validate: false,
    next: true,
    hint: '(22) 2222 2222',
    keyboardType: 'numeric',
    textContentType: 'none',
    inputType: 'text',
    group: 'dados_pessoais'
  },
  {
    name: 'email',
    label: 'Email',
    width: '100%',
    required: false,
    validate: [validateEmail],
    next: true,
    keyboardType: 'email-address',
    textContentType: 'emailAddress',
    autoCapitalize: 'none',
    parse: 'trim',
    inputType: 'text',
    group: 'dados_pessoais'
  },
  {
    name: 'rg',
    label: 'RG',
    width: winWidth <= 360 ? '100%' : '48%',
    required: false,
    maxLength: 15,
    validate: false,
    next: true,
    hint: 'Digite apenas números',
    keyboardType: 'numeric',
    textContentType: 'none',
    inputType: 'text',
    group: 'dados_pessoais'
  },
  {
    name: 'data_nascimento',
    label: 'Data de Nasc.',
    width: winWidth <= 360 ? '100%' : '48%',
    required: false,
    maxLength: 10,
    format: 'dt-br',
    validate: false,
    next: true,
    hint: 'DD/MM/YYYY',
    keyboardType: 'numeric',
    textContentType: 'none',
    inputType: 'text',
    group: 'dados_pessoais'
  },
  {
    name: 'cep',
    label: 'CEP',
    width: '100%',
    required: false,
    maxLength: 8,
    validate: false,
    next: true,
    hint: 'Digite apenas números.',
    keyboardType: 'numeric',
    textContentType: 'none',
    inputType: 'text',
    group: 'endereco'
  },
  {
    name: 'logradouro',
    label: 'Endereço',
    width: '100%',
    required: false,
    validate: false,
    next: true,
    keyboardType: 'default',
    textContentType: 'none',
    autoCapitalize: 'words',
    inputType: 'text',
    group: 'endereco'
  },
  {
    name: 'numero',
    label: 'Número',
    width: '33%',
    required: false,
    validate: false,
    next: true,
    keyboardType: 'numeric',
    textContentType: 'none',
    inputType: 'text',
    group: 'endereco'
  },
  {
    name: 'complemento',
    label: 'Complemento',
    width: '63%',
    next: true,
    keyboardType: 'default',
    textContentType: 'none',
    autoCapitalize: 'words',
    inputType: 'text',
    group: 'endereco'
  },
  {
    name: 'bairro',
    label: 'Bairro',
    width: '100%',
    required: false,
    validate: false,
    next: true,
    keyboardType: 'default',
    textContentType: 'none',
    inputType: 'text',
    group: 'endereco'
  },
  {
    name: 'cidade',
    label: 'Cidade',
    width: '63%',
    required: false,
    validate: false,
    next: true,
    keyboardType: 'default',
    textContentType: 'none',
    inputType: 'text',
    group: 'endereco'
  },
  {
    name: 'estado',
    label: 'UF',
    width: '33%',
    required: false,
    next: false,
    maxLength: 2,
    validate: false,
    keyboardType: 'default',
    textContentType: 'none',
    inputType: 'text',
    group: 'endereco'
  }
];